version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: no
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/diemdanh_stu?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      - MYSQL_DATABASE=diemdanh_stu
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: